#--------------------------------------------------------------------------#
#                                                                          #
#              _____ _____         _   _____ _         _                   #
#             | __  |  _  |___ ___| |_| __  | |___ ___| |_ ___             #
#             |    -|   __|  _| . |  _| __ -| | . |  _| '_|_ -|            #
#             |__|__|__|  |_| |___|_| |_____|_|___|___|_,_|___|            #
#                                                                          #
#        _          ____          _   _____           _     ___ ___        #
#       | |_ _ _   |    \ ___ ___| |_|  _  |___ ___ _| |___|_  |_  |       #
#       | . | | |  |  |  | .'|  _| '_|   __| .'|   | . | .'| | |_  |       #
#       |___|_  |  |____/|__,|_| |_,_|__|  |__,|_|_|___|__,| |_|___|       #
#           |___|                                                          #
#                                                                          #
#--------------------------------------------------------------------------#

#---{File version}
#
# DON'T TOUCH THIS SECTION! You can move it, but you can't remove this sections
# or change its values. This values are used to manage the different versions of
# this file. New files with newer versions uses this part to check if the file is
# new or old, and change the format to the new one.
#
#---

Version: 5

Settings: 
  
  Debug: 
    
    #---
    # If enabled, the plugin will start showing the enabled debug messages. On the
    # section below, you can allow the log of some specific messages in console.
    #---
    Enabled: "false"
    
    Messages: 
      Protection-creation-attempt: "true"
      Protection-creation: "true"
      Protection-removal-attempt: "true"
      Protection-removal: "true"
      Block-place: true
      Block-place-not-protection-block: true
      Block-place-is-protection-block: true
      Block-place-cancelled-build: true
      Block-place-cancelled: true
      Block-break: true
      Block-break-cancelled: true
      Oraxen-block-place: true
      Oraxen-block-break: true
      Itemsadder-block-place: true
      Itemsadder-block-break: true
      
  #---
  # Specify settings for your protections for every protection related setting on your server.
  #---
  Protection: 
    
    #---
    # Specify the ID of the block you wish to give people the first time they join the server.
    #---
    Starter-block: ""
    
    #---
    # Specify amount of time in seconds which will last the /pb view command. This command can be
    # cancelled by executing /pb view again, the timer is only made to remove the boundaries
    # after a while.
    #---
    Boundaries-view-duration-in-seconds: 30
    
    #---
    # Specify the default flags that will be set on every protection when they are created.
    # Remember to specify values that are valid for this flags. Currently, StateFlags, StringFlags
    # and CommandStringFlags are the only flags available to be specified.
    #---
    Default-flags: 
      greeting: "&7Entering protection from &a%player_name%"
      farewell: "&7Leaving protection from &a%player_name%"
      console-command-on-entry: "/title \%username\% actionbar {\"text\":\"&7Entering protection from &a%player_name%\"}"
      console-command-on-exit: "/title \%username\% actionbar {\"text\":\"&7Leaving protection from &a%player_name%\"}"
      
    Send-to-world-on-kick: "world"

    Set-player-position-as-home-on-creation: true

    Open-inventory-on-interact: true

    #---
    # Specify the automatic purge of protections which are from players that didn't play for at least the
    # specified amount of time. If the 'Execute-every' setting is empty, the auto removal will be disabled.
    #
    #   s -> Seconds
    #   m -> Minutes
    #   h -> Hours
    #   d -> Days
    #   w -> Weeks
    #   M -> Months (30 days)
    #   y -> Years (365 days)
    #
    #---
    Auto-purge: 
      Execute-every: ""
      Purge-older-than: "7d"
  
  #---
  # Add here all the worlds you don't wish people to be able to use protection blocks
  #---
  
  Banned-worlds: 
  - "World1"
  - "World2"
  - "World3"
  
  #---
  # Add here all the flags you wish to allow people to be editable on their protection
  # blocks. To get a list of the available flags, use /rg flags inside a region. The
  # structure of the configuration is the following one:
  #   <Flag name>:
  #     Type: <Material name>
  #     Amount: <Item amount>
  #     Name: <Name of the item> [Optional]
  #     Lore: [Optional]
  #     - <Lore>
  #     - <Of the item>
  #     Skin: <Skin of the item> [Optional]
  #     Group: <WorldGuard group where it should work> (Available: all, members, owners, non_members, non_owners) [Optional]
  #---
  
  Flags: 
    tnt: 
      Type: "PLAYER_HEAD"
      Amount: 1
      Name: "&eCan TnT explode?"
      Lore: 
      - "&0"
      - "&7Value: &8[&7{value}&8]"
      Skin: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOWU0MzUyNjgwZDBiYjI5YjkxMzhhZjc4MzMwMWEzOTFiMzQwOTBjYjQ5NDFkNTJjMDg3Y2E3M2M4MDM2Y2I1MSJ9fX0="
    chest-access: 
      Type: "PLAYER_HEAD"
      Amount: 1
      Name: "&eCan chests be opened by others?"
      Lore: 
      - "&0"
      - "&7Value: &8[&7{value}&8]"
      Skin: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZWRjMzZjOWNiNTBhNTI3YWE1NTYwN2EwZGY3MTg1YWQyMGFhYmFhOTAzZThkOWFiZmM3ODI2MDcwNTU0MGRlZiJ9fX0="
      Group: "non_members"
    pvp: 
      Type: "PLAYER_HEAD"
      Amount: 1
      Name: "&eIs PvP allowed?"
      Lore: 
      - "&0"
      - "&7Value: &8[&7{value}&8]"
      Skin: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTc2NTM0MTM1M2MwMjllOWI2NTVmNGY1NzkzMWFlNmFkYzJjN2E3M2M2NTc5NDVkOTQ1YTMwNzY0MWQzNzc4In19fQ=="
      
  #---
  # Define which commands should be executed when a protection is created
  # or removed.
  #---
  
  Commands-on-creation: []
  Commands-on-removal: []
  
Commands: 
  Protection-blocks: 
    Name: "protectionblocks"
    Description: "Open the GUI or execute commands"
    Usage: "[help|subcommand]"
    Permission: ""
    Aliases: 
    - "pb"
    List: 
      Name: "list"
      Description: "Open a list with all your protections"
      Usage: ""
      Permission: ""
      Aliases: 
      - "l"
    Add-member: 
      Name: "addmember"
      Description: "Add a member on your current protection"
      Usage: "<username>"
      Aliases: 
      - "am"
      Permission: ""
    Remove-member: 
      Name: "removemember"
      Description: "Remove a member on your current protection"
      Usage: "<username>"
      Permission: ""
      Aliases: 
      - "rm"
    Add-owner: 
      Name: "addowner"
      Description: "Add an owner on your current protection"
      Usage: "<username>"
      Permission: ""
      Aliases: 
      - "l"
    Remove-owner: 
      Name: "removeowner"
      Description: "Remove an owner on your current protection"
      Usage: "<username>"
      Permission: ""
      Aliases: 
      - "l"
    Reload: 
      Name: "reload"
      Description: "Reload the plugin"
      Usage: ""
      Permission: "ProtectionBlocks.Reload"
      Aliases: 
      - "rd"
    Rename: 
      Name: "rename"
      Description: "Rename your current protection name"
      Usage: "<new name>"
      Permission: ""
      Aliases: 
      - "rn"
    Set-home: 
      Name: "sethome"
      Description: "Set the home on your current protection"
      Usage: ""
      Permission: ""
      Aliases: 
      - "sh"
    Blocks: 
      Name: "blocks"
      Description: "Open a list with all the blocks"
      Usage: "[help|subcommand]"
      Permission: "ProtectionBlocks.Blocks"
      Aliases: 
      - "b"
      Add: 
        Name: "add"
        Description: "Create a new block"
        Usage: "<id> <x> <y> <z> [permission]"
        Permission: "ProtectionBlocks.Blocks.Create"
        Aliases: 
        - "a"
      Remove: 
        Name: "remove"
        Description: "Remove an existing block"
        Usage: "<id>"
        Permission: "ProtectionBlocks.Blocks.Delete"
        Aliases: 
        - "r"
      Give: 
        Name: "give"
        Description: "Give an existing block to yourself or a player"
        Usage: "<id> [player]"
        Permission: "ProtectionBlocks.Blocks.Give"
        Aliases: 
        - "g"
    Hide: 
      Name: "hide"
      Description: "Hide the protection block on your current protection"
      Usage: ""
      Permission: ""
      Aliases: 
      - "h"
    Show: 
      Name: "show"
      Description: "Show the protection block on your current protection"
      Usage: ""
      Permission: ""
      Aliases: 
      - "sw"
    View: 
      Name: "view"
      Description: "Show the boundaries of your current protection for a certain time"
      Usage: ""
      Permission: ""
      Aliases: 
      - "v"
    Ban: 
      Name: "ban"
      Description: "Ban a player from your current protection"
      Usage: "<username>"
      Permission: ""
      Aliases: 
      - "bn"
    Unban: 
      Name: "unban"
      Description: "Unban a player from your current protection"
      Usage: "<username>"
      Permission: ""
      Aliases: 
      - "ubn"
    Kick: 
      Name: "kick"
      Description: "Kick a player from your current protection"
      Usage: "<username>"
      Permission: ""
      Aliases: 
      - "k"
    Transfer: 
      Name: "transfer"
      Description: "Transfer data from a plugin to RoyaleProtectionBlocks"
      Usage: "[plugin to transfer] <confirm>"
      Permission: "protectionblocks.transfer"
      Aliases: 
      - "t"
    Files: 
      Name: "files"
      Description: "Manage the importation and exportation of data through files"
      Usage: "[help|subcommand]"
      Permission: "protectionblocks.files"
      Export: 
        Name: "export"
        Description: "Export all the information of an specific type of data to its respective
          file"
        Usage: "<blocks>"
        Permission: "protectionblocks.files.export"
        Aliases: 
        - "e"
      Import: 
        Name: "import"
        Description: "Import all the information of an specific type of data from its respective
          file"
        Usage: "<blocks>"
        Permission: "protectionblocks.files.import"
        Aliases: 
        - "i"
      Aliases: 
      - "f"
    Purge: 
      Name: "purge"
      Description: "Delete protections older than the specified time, based on the last
        connection of the owner or their creation date"
      Usage: "[--days <amount of days>] [--hours <amount of hours>] [--minutes
        <amount of minutes>] [--config] [confirm]"
      Permission: "protectionblocks.purge"
      Aliases: 
      - "p"
  Generic: 
    Help: 
      Name: "help"
      Description: "Get all the commands"
      Usage: "[page]"
      Permission: ""
      Aliases: 
      - "h"