main: ${project.package}.${project.groupId}.Plugin.MainPluginClass
name: ${project.name}
author: ${project.author}
version: ${project.spigotVersion}
description: ${project.description}
api-version: 1.13
depend: [ WorldGuard ]
softdepend: [ PlaceholderAPI, ItemsAdder, ProtectionStones, Oraxen, DeluxeCombat, LuckPerms, CombatLogX, PvPManager, ProtocolLib, Vault, TokenManager, EssentialsX, CoinsEngine, PlayerPoints ]

permissions:
  protectionblocks.teleport:
    default: true