main: ${project.package}.${project.groupId}.Plugin.MainPluginClass
name: ${project.name}
author: ${project.author}
version: ${project.version}
description: ${project.description}
api-version: 1.13
depend: [ WorldGuard ]
softdepend: [ PlaceholderAPI, ItemsAdder, ProtectionStones, Oraxen, DeluxeCombat, LuckPerms, Vault, TokenManager, CombatLogX, PvPManager ]

permissions:
  protectionblocks.teleport:
    default: true