Title: "Player Settings"
Size: 27
Messages:
  Invitation-requirement:
    All-accepted: "All invitations accepted"
    All-denied: "All invitations denied"
    Invitation-required: "Invitation required"
  Common:
    Enabled: "&aEnabled"
    Disabled: "&cDisabled"
Items: 
  Background: 
    Display-item: 
      Type: "GRAY_STAINED_GLASS_PANE"
      Amount: 1
      Name: "&0"
    Slots: "0-26"
  Player-info:
    Display-item:
      Type: "PLAYER_HEAD"
      Amount: 1
      Name: "&e{player_name}"
    Slots: "10"
  Auto-flight-button:
    Display-item:
      Type: "FEATHER"
      Amount: 1
      Name: "&eAuto-flight &8[&7{autoflight_value}&8]"
    Slots: "13"
  Invitation-requirement-button:
    Display-item:
      Type: "PLAYER_HEAD"
      Amount: 1
      Name: "&eInvitation requirement &8[&b{invitationrequirement_value}&8]"
      Skin: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzQ1ZmQxNzRmMjUwMzdiN2Y5ZWNhNzMzY2ZkMDQ2YThiNjM1MTEyMDI2NDg1MzcwNWJjYWE1YjYzZTE3YzE3In19fQ=="
    Slots: "16"
  Back-button:
    Display-item:
      Type: "PLAYER_HEAD"
      Amount: 1
      Name: "&cBack"
      Skin: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTljZGI5YWYzOGNmNDFkYWE1M2JjOGNkYTc2NjVjNTA5NjMyZDE0ZTY3OGYwZjE5ZjI2M2Y0NmU1NDFkOGEzMCJ9fX0="
    Slots: "18"